apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::391733008457:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-3NrAWtBKUgyV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::391733008457:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-03T06:38:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3221"
  uid: f63a7f5b-f7ff-4271-be54-aedd93ce93fd
